### ISSUE TITLE
Where to find the  'libSDL2.so' 

### ISSUE THREAD

**Issue by piXelicidio** [TetrisSQC/YaSE#1]
Hi, where I find or how to compile the  'libSDL2.so'  library?
There is no official download for android binaires on SDL2 website.
Thank you.

**Comment by TetrisSQC** [comment]
Actually it is pretty simple to compile by yourself. Anyway the attached libs are the builds i usually use for Android.

[SDL Android.zip](https://github.com/TetrisSQC/YaSE/files/3226616/SDL.Android.zip)
